# -*- coding: utf-8 -*-
"""internal

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T3BgpAlUjRnXjZXxt7yf-xVx9ePGJcUH
"""

print("""I am signing up for Replit&#39;s 100 days of Python challenge! I will make sure to spend
some time every day coding along, for a minimum of 10 minutes a day. I&#39;ll be using
Replit, an amazing online IDE so I can do this from my phone wherever I happend to be.
No excuses for not coding from the middle of a field!""")

malware={'ransomeware':'RYUK','fileless':'Astaroth','spyware':'Darkhotal','adware':'fireball'}
print(malware)
print(malware.values())
print(malware.items())
print(malware.keys())
print(malware.clear())

def household():
   print("\n Calculating household Eb price")
   unit=int(input("\n number of units used:"))
   if unit<100:
      price=0.50
      print("your price : Rs", price)
   elif unit>101 and unit<200:
      price = unit*0.75 
      print("your price : Rs", price)
   elif unit>201 and unit<300:
      price = unit*1.20 
      print("your price : Rs", price) 
household()

weight = int(input());
height = float(input());
x = weight/float(height*height);
if x < 18.5:
    print('Underweight')
if x>=18.5 and x<25:
    print("Normal")
if x >= 25 and x < 30:
   print('Overweight')

amount=int(input("price:"))
per=int(input("percentage:"))
GST=amount*per/100
total=amount+GST
print("GST:",GST)
print("total:",total)

import pandas as pd
student_data=pd.DataFrame(
    {"Student_Name": ["Rajesh", "Vishnu", "Yogeshpandian", "Kottai", "Yogeshwaran", "Gulfum", "Boobathy", "Goodson", "Periyasamy", "Murali"],
     "Age": [20,21,22,23,24,25,26,27,28,29],
     "DOB(year)": [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010],
     "Weight(kg)" : [72,95,75,56,98,55,70,62,70,65],
     "Height(cm)" : [150,140,125,157,156,188,199,154,177,133]}
)

student_data["BMI"]=student_data["Weight(kg)"]/student_data["Height(cm)"]*student_data["Height(cm)"]

student_data["Status"]=student_data["BMI"].apply(lambda x: "Normal" if x>50 and x<80 else "Underweight")
print(student_data)